# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=$POSTGRES_USERNAME
export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
export POSTGRES_HOST=$POSTGRES_HOST
export POSTGRES_DB=$POSTGRES_DB
export AWS_BUCKET=$AWS_BUCKET
export AWS_REGION=$AWS_REGION
export AWS_PROFILE=$AWS_PROFILE
export JWT_SECRET=$JWT_SECRET
export URL=$URL